### ISSUE TITLE
Github issues: cannot edit files on website

### ISSUE THREAD

**Issue by LNFWebsite** [stereobooster/github-issues#19]
I host https://github.com/LNFWebsite/Streamly and cannot submit edits to files online (submit button is shaded)...

Here's the output of my console log:

```
frameworks-723b8dc38ba1ad03fd0826f759f90949dd32eb61188516803678ede79ab8d269.js:5 Uncaught Error: Could not find module github/sliding-promise-queue

github-ec5b4ee5f3c0c6fed52b30e4816ec4a794e29e3c98caa0c819d5431de226e0c2.js:1 Uncaught TypeError: t is not a function
```

Hopefully this can be resolved easily...

**Comment by LukeLR** [comment]
So you're trying to edit a file with the GitHub integrated online editor?

Am 03.12.2015 um 22:59 schrieb LNFWebsite:

**Comment by LNFWebsite** [comment]
Yeah, and the commit button is shaded...

**Comment by LNFWebsite** [comment]
Holdup... Looks like it's working again... Let me make sure before I close this issue...

**Comment by LNFWebsite** [comment]
Nope, it's still doing it...

**Comment by LNFWebsite** [comment]
The commit button is shaded even when I have typed edits in the file.

I was just using this earlier today and it was working fine. Maybe you guys had a bug in an update that you did?

**Comment by LNFWebsite** [comment]
Just tried to edit in both of my repos, but both give the error that I gave you and continuously have the button shaded out...

**Comment by LNFWebsite** [comment]
@LukeLR You still here?

**Comment by LNFWebsite** [comment]
@LukeLR Seems like its working again. Thanks for the help!

**Comment by LukeLR** [comment]
Yes, I'm still here ;) But good that it works again ;)
